### ISSUE TITLE
How to handle the expired authentication token ?

### ISSUE THREAD

**Issue by jgaucher-cs** [radiantearth/stac-browser#523]
Hi, I'm using the stac-browser with the OpenID/OAuth2 authentication as explained here: https://github.com/radiantearth/stac-browser/issues/479

So the first time the stac-browser connects to our backend, the backend returns a 401 error to tell the stac-browser to authenticate: the stac-browser connects to our keycloak/oauth2 server, retrieves a token, connects again to our backend by giving the token in the http Authorization header, our backend reads the token and sends back the user-allowed data. All this works very well.

But the token as an expiration time of 5 minutes. When the user refreshes the page or opens a new page (by e.g. clicking on a collection link), the stac-browser requests a new token every time (from our oauth2 server) with a new 5-minutes expiration time, so this works well also. The problem is when we use the stac-browser /search page and click on the "Submit" button at the bottom: this time the page is not refreshed, and the same token is used, but after 5 minutes it has expired and our python backend raises an exception.

I've tried to catch this exception from our backend and return a 401 error to the stac-browser to tell it to authenticate again, as we do for the first login, but this doesn't work: the stac-browser just displays the 401 error, but it does not authenticate. I guess this 401 error works well when sent from our backend service root url, not from our backend /search endpoint. Please see attached screenshot below.

Would you know how my backend service could tell the stac-browser to refresh the token from the /search page ?

![image](https://github.com/user-attachments/assets/a7487246-85c4-4a19-82ed-7e079f9878a5)

What we see in this screenshot is that the first call from the stac-browser to our service root url `127.0.0.1` returned a 401 error, which told the stac-browser to authenticate, which it did (see the following calls to `openid-configuration`). The last call from the stac-browser to our service `/search` endpoint also returned a 401 error, but this time the stac browser does not authenticate again, it just displays the error message in the bottom-left of the page.

 Thank you :)

**Comment by m-mohr** [comment]
I assume the refresh token is used to get new tokens every 5 minutes? Or does it actually reauthenticates every time? (5 minutes seems really short btw.) Is it only refreshed on page navigation? Or also if you leave a collection or item open for 5+ minutes?

I'm not sure why this doesn't happen from the Search page. Clicking the search button is not a navigation as the other page changes. Do you have an instance where I could test this? Without a reproducible example I'm not able to help, I'm afraid.

**Comment by jgaucher-cs** [comment]
Hi @m-mohr and thank you for your response. I'm trying to understand how it works in https://browser.stac.dataspace.copernicus.eu/search. When I'm logging in, I can see that the stac-browser calls the auth service https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token to ask for a token. 

![image](https://github.com/user-attachments/assets/365bff41-b2f9-40a3-8ebe-1b522fb8e884)

The payload is: 
```
grant_type: authorization_code
redirect_uri: https://browser.stac.dataspace.copernicus.eu/auth
code: 42f1e7ab-...-a11188aa6a7d
code_verifier: 71434...c4bb2
client_id: stac-browser
```

The response is:
```json
{
    "access_token": "eyJhb...OK77Q",
    "expires_in": 600, // 10 minutes
    "refresh_expires_in": 3600, // 1 hour
    "refresh_token": "eyJhb...U2U2g",
    "token_type": "Bearer",
    "id_token": "eyJhb...bOMQg",
    "not-before-policy": 0,
    "session_state": "11b6d5e0-...-c765fd9185e0",
    "scope": "AUDIENCE_PUBLIC openid email profile user-context"
}
```

The access_token contains my authentication and authorization, it is valid for 10 minutes. After that, we will have to refresh this token. But for now, I see that this access_token is passed in the Authorization header when calling the backend /search endpoint:

![image](https://github.com/user-attachments/assets/be8e6cfa-ead5-49bd-bdbd-73f4c4d2f87d)

(The Authorization header is: "Bearer eyJhb...OK77Q" = the access_token retrieved in the previous step)

After a few minutes, we can see that the stac-browser automatically calls the token service again to refresh the token, which is nice. 

![image](https://github.com/user-attachments/assets/55fdf8d5-b715-4a75-99ef-edc28c336227)

The url is still https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token but the payload is different:
```
grant_type: refresh_token
refresh_token: eyJhb...U2U2g # = the refresh_token retrieved in the previous step
scope: AUDIENCE_PUBLIC openid email profile user-context
client_id: stac-browser
```

The response is:
```json
{
    "access_token": "eyJhb...It_wQ", // we have a new access_token !
    "expires_in": 600,
    "refresh_expires_in": 3600,
    "refresh_token": "eyJhb...xDVxE",
    "token_type": "Bearer",
    "id_token": "eyJhb...9A_3Q",
    "not-before-policy": 0,
    "session_state": "11b6d5e0-...-c765fd9185e0",
    "scope": "AUDIENCE_PUBLIC openid email profile user-context"
}
```

So you would expect the stac-browser to use this new access_token when calling the /search endpoint again. But no, even after 10 minutes or long after that, it still uses the old access_token retrieved from the first step !

![image](https://github.com/user-attachments/assets/cf284682-fac8-45d7-b8ea-2c45cb4636ca)

(The Authorization header is: "Bearer eyJhb...OK77Q" = still the old access_token)

This access_token is expired but still seems to be accepted by the CSDE backend. To be confirmed by them maybe. I don't have any error in my browser, but maybe it doesn't return my authorized data anymore, I'm not sure.

So I have two questions here: 

  1. Is it normal that the stac-browser gives the old access_token in the Authorization header instead of the new/refreshed one ?
  2. (maybe out of scope of this issue, but if you have the response it would be nice) how the CSDE backend handles this expired token ? (in my service I've tried to save the old token in a cookie but they are reset for each new /search request, I don't know why).

Thank you :)

**Comment by m-mohr** [comment]
Thanks for the investigation, this will help to nail down the issue. I'll follow-up!

**Comment by m-mohr** [comment]
@jgaucher-cs I think #525 should solve the issue. I tested it on CDSE and it uses the new token as far as I can tell. If it also works for you, I'd merge it and release with v3.3.0 in the next days. Thanks for the analysis work!

**Comment by ThorodanBrom** [comment]
I was facing the same problem and [tried to fix it](https://github.com/datakaveri/stac-browser/commit/36f57b5e59dafe174e4f913bbcd6c879f44f2260#diff-a65ec45dd288de855d16aa0064f83540f113d7db397f9a497b4f8d2e81a6a0edR20) in a hacky way which seemed to work. #525 fixes the issue (for me at least), thanks @m-mohr!

**Comment by jgaucher-cs** [comment]
Thank you very much @m-mohr, your fix works for me ! I still have a question about the refresh_token: we see in my above screenshot that the token is refreshed between calls to the /search endpoint. But I'm not sure when this refresh happens, it seems more or less random. My token lifetime is 5 minutes. Can I be sure that it will be refreshed before 5 minutes ?

**Comment by vprivat-ads** [comment]
@jgaucher-cs according to https://github.com/authts/oidc-client-ts/blob/v3.1.0/src/UserManagerSettings.ts#L52 the refresh should be done 1 minute prior expiration thanks to the automaticSilentRenew flag.

**Comment by m-mohr** [comment]
Thanks for the feedback. Merged the PR. Will be released soon as v3.3.0.
